version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sturdy-space-doodle
      MYSQL_DATABASE: SupermarketListGeneratorDatabase
      MYSQL_USER: administrator
      MYSQL_PASSWORD: jean-philippe-mateta
    ports:
      - "3306:3306"

# docker-compose exec db mysql -u administrator -p SupermarketListGeneratorDatabase